Prepare jiralert for Criteo usage
criteo-forks/jiralerts pull request #1
Opened 2018-01-25 09:05 UTC by Thib17

2018-01-25 11:27 UTC, iksaif requested changes

2018-01-25 11:27 UTC, iksaif commented on main.py
> +summary_tmpl = JINJA_ENV.get_template('templates/summary')
summary.tmpl instead of just summary ?

2018-01-25 11:27 UTC, iksaif commented on main.py
> +search_query = 'project = %s and labels = "jiralerts" and status not in (%s) and description ~ "alert_group_key=%s"'
why do we need to change the label ?

2018-01-25 11:27 UTC, iksaif commented on main.py
> +@click.option('--res_trans', default="resolve issue,close issue",
/trans/transitions/

2018-01-29 12:45 UTC, iksaif approved these changes

2018-01-29 12:50 UTC, InformatiQ commented
LGTM

2018-01-29 12:55 UTC, merged